# Generated by Django 4.1.4 on 2023-07-26 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0005_remove_user_registration_pro_pic_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('buying_count', models.IntegerField()),
                ('offer', models.FloatField()),
                ('image', models.FileField(default='static/images/default.png', upload_to='images/items')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NadaliyaApp.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('buying_count', models.IntegerField()),
                ('offer', models.FloatField()),
                ('image', models.FileField(default='static/images/default.png', upload_to='images/items')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NadaliyaApp.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NadaliyaApp.user_registration')),
            ],
        ),
    ]
