# Generated by Django 4.1.4 on 2023-07-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0006_item_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='buying_count',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rating',
        ),
    ]
