# Generated by Django 4.1.4 on 2023-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0007_remove_cart_buying_count_remove_cart_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
